### ISSUE TITLE
Ability to disable migrations

### ISSUE THREAD

**Issue by Myster** [AffinityID/uMigrate#2]
Scenario Example:
I have a migration to delete a content type.
Someone does this manually just before I release to production.
The migration will cause an exception making the app unusable.
If I could disable the migration framework from running on start-up I could go into the back office and create the item so I don't have to revert (perhaps previous migrations already ran in this deployment)

Perhaps this is another gun with which to shoot your foot, but as they say, "It's my foot"

BTW: I don't see how to delete a content type with uMigrate, so I put the relevant calls to the Umbraco core ContentTypeService in the migration step.

**Comment by ashmind** [comment]
@Myster This can be solved in different ways. Right now you should be able to temporarily disable migrations by deleting uMigrate from the application bin folder. Do you want a config setting instead (it would require same level of access to the server)?

As for deleting already deleted -- uMigrate can handle most of already-performed changes by design --  but you are right that we haven't implemented Delete() yet. I'll take a look at implementing it in a reliable way in a future version.

**Comment by Myster** [comment]
If I had put my migrations into their own DLL that would work, And actually I should do that.
However, I think the flexibility of a configuration setting would be best.
Consider someone using visual studio express which only allows one project. (or did last time I looked)

**Comment by ashmind** [comment]
@Myster What I mean is that you could delete uMigrate/uMigrate.UI dlls, which should exclude them from Umbraco startup events discovery. But I'll consider how we can improve this.

**Comment by Myster** [comment]
I tried removing uMigrate.UI.dll from the bin folder but it still triggered the NotImplementedException I have in the Run method of my migration.

**Comment by ashmind** [comment]
You'll have to delete both uMigrate.dll and uMigrate.UI.dll.
